apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-demo-config
  namespace: fleet-demo
data:
  version: "5.0"
  message: "Cambio mientras Fleet estaba pausado. Prueba para Fleet Agent, segundo intento."
